// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV43mwauAG2vpvIqToqaXA95Dm42ujzZY',
    appId: '1:67883710854:web:99123b7543fddc574cd407',
    messagingSenderId: '67883710854',
    projectId: 'legidoc-f50a9',
    authDomain: 'legidoc-f50a9.firebaseapp.com',
    storageBucket: 'legidoc-f50a9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK2M4clcQ9em25f3pDX0_n_8C3DSPJmck',
    appId: '1:67883710854:android:3e79d51b748e27154cd407',
    messagingSenderId: '67883710854',
    projectId: 'legidoc-f50a9',
    storageBucket: 'legidoc-f50a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA09R9BcurEJBKg8TEKXMsNMubwtIvRGN0',
    appId: '1:67883710854:ios:4d78fcd62eb891c74cd407',
    messagingSenderId: '67883710854',
    projectId: 'legidoc-f50a9',
    storageBucket: 'legidoc-f50a9.appspot.com',
    iosBundleId: 'com.example.dockable',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA09R9BcurEJBKg8TEKXMsNMubwtIvRGN0',
    appId: '1:67883710854:ios:67b1d211cab1dc4e4cd407',
    messagingSenderId: '67883710854',
    projectId: 'legidoc-f50a9',
    storageBucket: 'legidoc-f50a9.appspot.com',
    iosBundleId: 'com.example.dockable.RunnerTests',
  );
}
